version: '3.7'
#services
services:
  #Google SQL Proxy so we can connect to our databse in the cloud
  cloud_db:
      container_name: cloud_db
      image: gcr.io/cloudsql-docker/gce-proxy:latest
      command: /cloud_sql_proxy --dir=/cloudsql -instances=main-283505:us-central1:startupcode=tcp:0.0.0.0:3306 -credential_file=/secrets/cloudsql/key.json
      ports:
        - 3306:3306
      volumes:
        - /home/carl/key.json:/secrets/cloudsql/key.json
      restart: always
  #web app running on top of alpine
  web:
    build: .
    environment:
      # You must set an URL to access your database. On sequelize (nodejs) it follows this
      # format: db-type://user:password@host:port/database-name
      # the one below is for a MySQL database.
      DATABASE_URL: mysql://carl:aababot2323@cloud_db:3306/AuthDB
    ports:
      - 3000:3000
    depends_on: 
        - cloud_db
    